from collections.abc import Iterable
from pathlib import Path
import sys

import anki
import anki.collection
import anki.models
import anki.notes
import anki.hooks

from rich import print  # noqa: A004

from duo_scrapo.Morf import VerbForms


class ModelAlreadyExistsError(Exception):
    def __init__(self, message: str = "Model already exists"):
        self.message = message
        super().__init__(self.message)


# Generated by Copilot
def add_fields_to_note_type(col: anki.collection.Collection, note_type: anki.models.NoteType, field_names: Iterable[str]) -> None:
    """
    Adds fields to the given NoteType in the provided Collection.

    Parameters:
    col (anki.collection.Collection): The Anki collection.
    note_type (anki.models.NoteType): The NoteType to which fields will be added.
    field_names (Iterable[str]): An iterable of field names to add to the NoteType.
    """
    mm = col.models
    for field_name in field_names:
        field = mm.new_field(field_name)
        mm.add_field(note_type, field)


filepath = Path.cwd() / "output.anki2"
if filepath.exists():
    filepath.unlink()

col = anki.collection.Collection(filepath.as_posix())
czasowniki = col.models.by_name("Czasowniki")


if czasowniki is not None:
    raise ModelAlreadyExistsError()

if czasowniki is None:
    # Create a new Note Type using ModelManager
    mm = col.models
    new_note_type = mm.new("Czasowniki")

    # Add fields to the Note Type
    # mm.add_field(new_note_type, mm.new_field("Front"))
    # mm.add_field(new_note_type, mm.new_field("Back"))
    add_fields_to_note_type(col, new_note_type, ("pl", "en"))
    add_fields_to_note_type(col, new_note_type, VerbForms.get_cols())

    # Add templates to the Note Type
    template = mm.new_template("Card 1")
    template['qfmt'] = "{{en}}"  # Question format
    template['afmt'] = "{{FrontSide}}<hr id=\"answer\">{{pl}}"  # Answer format
    new_note_type['tmpls'].append(template)

    # Add the new Note Type to the collection
    mm.add(new_note_type)

czasowniki = col.models.by_name("Czasowniki")
if czasowniki is None:
    print("Model not found")
    sys.exit(0)

outpath = Path.cwd() / "czasowniki.apkg"

col.export_anki_package(
    out_path=outpath.as_posix(),
    limit=None,
    options=anki.collection.ExportAnkiPackageOptions(),
)
