from _typeshed import SupportsNext
from sqlite3 import Cursor
"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""

class Card:
    def __init__[T](self, ord_: int, suspend: SupportsNext[T] = ...) -> None: ...

    def write_to_db[T](
        self, cursor: Cursor, timestamp: float, deck_id: int, note_id: int, id_gen: SupportsNext[T], due: int = ...
    ) -> None: ...
