from collections.abc import Iterable, Mapping
"""
This type stub file was generated by pyright.
"""

type Field = dict[str, str]
type Template = dict[str, Field]

class Model:
    FRONT_BACK = ...
    CLOZE = ...
    DEFAULT_LATEX_PRE = ...
    DEFAULT_LATEX_POST = ...

    def __init__(
        self,
        model_id: int | None = None,
        name: str | None = None,
        fields: list[Field] | None = None,
        templates: list[Template] | str | None = None,
        css: str = "",
        model_type: int = FRONT_BACK,
        latex_pre: str = DEFAULT_LATEX_PRE,
        latex_post: str = DEFAULT_LATEX_POST,
        sort_field_index: int = 0,
    ) -> None: ...

    def set_fields(self, fields: Iterable[Field]) -> None: ...

    def set_templates(self, templates: Mapping[str, Template]) -> None: ...

    def to_json(self, timestamp: float, deck_id: int) -> None: ...

    def __repr__(self) -> str: ...
